//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revisions
    {
        public int RevID { get; set; }
        public string Comment { get; set; }
    
        public virtual Datasets Datasets { get; set; }
        public virtual Revisions Revisions1 { get; set; }
        public virtual Revisions Revisions2 { get; set; }
    }
}
