//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataPointSet
    {
        public int DatapointId { get; set; }
        public decimal ProjectileCharge { get; set; }
        public int EqEnergy { get; set; }
        public int StoppingPower { get; set; }
        public string DataformatForEq { get; set; }
        public decimal ConvertetData { get; set; }
        public Nullable<int> DataformatId { get; set; }
    
        public virtual DataformatSet DataformatSet { get; set; }
        public virtual DatasetSet DatasetSet { get; set; }
    }
}
