//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatasetSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatasetSet()
        {
            this.ArticleReferencesSet = new HashSet<ArticleReferencesSet>();
            this.DataPointSet = new HashSet<DataPointSet>();
            this.MethodSet = new HashSet<MethodSet>();
            this.RevisionSet = new HashSet<RevisionSet>();
        }
    
        public int DatasetId { get; set; }
        public Nullable<int> UserUserId { get; set; }
        public int Material_MaterialId { get; set; }
        public int Ion_IonId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleReferencesSet> ArticleReferencesSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataPointSet> DataPointSet { get; set; }
        public virtual IonSet IonSet { get; set; }
        public virtual MaterialSet MaterialSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MethodSet> MethodSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RevisionSet> RevisionSet { get; set; }
        public virtual UserSet UserSet { get; set; }
    }
}
