//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevisionSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RevisionSet()
        {
            this.RevisionSet1 = new HashSet<RevisionSet>();
        }
    
        public int RevId { get; set; }
        public string Comment { get; set; }
        public int PrevRevision_RevId { get; set; }
        public int Dataset_DatasetId { get; set; }
    
        public virtual DatasetSet DatasetSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RevisionSet> RevisionSet1 { get; set; }
        public virtual RevisionSet RevisionSet2 { get; set; }
    }
}
