//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPDS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSPDSEntity : DbContext
    {
        public TSPDSEntity()
            : base("name=TSPDSConnectionstring")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArticleReferencesSet> ArticleReferencesSet { get; set; }
        public virtual DbSet<DataformatSet> DataformatSet { get; set; }
        public virtual DbSet<DataPointSet> DataPointSet { get; set; }
        public virtual DbSet<DatasetSet> DatasetSet { get; set; }
        public virtual DbSet<IonSet> IonSet { get; set; }
        public virtual DbSet<IsotopeSet> IsotopeSet { get; set; }
        public virtual DbSet<MaterialSet> MaterialSet { get; set; }
        public virtual DbSet<MethodSet> MethodSet { get; set; }
        public virtual DbSet<PermissionSet> PermissionSet { get; set; }
        public virtual DbSet<RevisionSet> RevisionSet { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserSet> UserSet { get; set; }
    }
}
